openapi: 3.0.3
info:
  title: GestEPM Core API
  version: 0.1.0
  description: GestEPM Core API
  contact:
    name: Carlos Devesa Pérez
servers:
  - url: 'http://localhost:8080'
paths:
  /v1/shares/no-programmed:
    get:
      summary: V1 - List no programmed shares
      responses:
        '200':
          $ref: '#/components/responses/NoProgrammedShareList'
      operationId: list-no-programmed-shares-v1
      description: list-no-programmed-shares-v1
      parameters:
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-meta
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-links
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-expand
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-offset
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-limit
      tags:
        - no-programmed-share-v1
    post:
      summary: V1 - Create no programmed share
      operationId: create-no-programmed-share-v1
      responses:
        '200':
          $ref: '#/components/responses/NoProgrammedShare'
        '404':
          description: user-not-found | project-not-found
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResError
      description: create-no-programmed-share-v1
      tags:
        - no-programmed-share-v1
      requestBody:
        $ref: '#/components/requestBodies/CreateNoProgrammedShare'
  '/v1/shares/no-programmed/{shareId}':
    parameters:
      - $ref: '#/components/parameters/Share-Id'
    get:
      summary: V1 - Find no programmed share
      tags:
        - no-programmed-share-v1
      responses:
        '200':
          $ref: '#/components/responses/NoProgrammedShare'
        '404':
          description: no-programmed-share-not-found
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResError
      operationId: find-no-programmed-share-by-id-v1
      description: find-no-programmed-share-by-id-v1
      parameters:
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-meta
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-links
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-expand
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-locale
    patch:
      summary: V1 - Update no programmed share
      operationId: update-no-programmed-share-v1
      responses:
        '200':
          $ref: '#/components/responses/NoProgrammedShare'
        '404':
          description: no-programmed-share-not-found
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResError
      description: update-no-programmed-share-v1
      tags:
        - no-programmed-share-v1
      requestBody:
        $ref: '#/components/requestBodies/UpdateNoProgrammedShare'
    delete:
      summary: V1 - Delete no programmed share
      operationId: delete-no-programmed-share-v1
      responses:
        '200':
          description: '**OK**'
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResSuccess
        '404':
          description: no-programmed-share-not-found
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResError
      description: delete-no-programmed-share-v1
      tags:
        - no-programmed-share-v1
  '/v1/shares/no-programmed/{shareId}/interventions':
    parameters:
      - $ref: '#/components/parameters/Share-Id'
    get:
      summary: V1 - List interventions
      tags:
        - no-programmed-share-v1
      responses:
        '200':
          $ref: '#/components/responses/InterventionList'
        '404':
          description: no-programmed-share-not-found
          content:
            application/json:
              schema:
                $ref: ../../base-api-spec.yaml#/components/schemas/ResError
      operationId: list-interventions-v1
      description: list-interventions-v1
      parameters:
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-meta
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-links
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-expand
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-offset
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-limit
    post:
      summary: V1 - Create intervention
      operationId: create-intervention-v1
      responses:
        '200':
          description: OK
      tags:
        - no-programmed-share-v1
      description: create-intervention-v1
  '/v1/shares/no-programmed/{shareId}/interventions/{interventionId}':
    parameters:
      - $ref: '#/components/parameters/Share-Id'
      - schema:
          type: string
        name: interventionId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-v1-shares-no-programmed-shareId-interventions-interventionId
    put:
      summary: ''
      operationId: put-v1-shares-no-programmed-shareId-interventions-interventionId
      responses:
        '200':
          description: OK
    delete:
      summary: ''
      operationId: delete-v1-shares-no-programmed-shareId-interventions-interventionId
      responses:
        '200':
          description: OK
  /v1/users:
    get:
      summary: V1 - List users
      responses:
        '200':
          $ref: '#/components/responses/UserList'
      operationId: list-users-v1
      description: list-users-v1
      parameters:
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-meta
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-links
        - $ref: ../../base-api-spec.yaml#/components/parameters/api-opt-expand
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-offset
        - $ref: ../../base-api-spec.yaml#/components/parameters/filter-pagination-limit
      tags:
        - user-v1
    post:
      summary: ''
      operationId: post-api-users
      responses:
        '200':
          description: OK
      tags:
        - user
    parameters: []
  '/v1/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: User id.
    get:
      summary: Your GET endpoint
      tags:
        - user
      responses: {}
      operationId: get-api-users-id
    put:
      summary: ''
      operationId: put-api-users-id
      responses:
        '200':
          description: OK
      tags:
        - user
    delete:
      summary: ''
      operationId: delete-api-users-id
      responses:
        '200':
          description: OK
      tags:
        - user
components:
  schemas:
    Family:
      title: Family
      x-stoplight:
        id: wr1b8bilbahz0
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          x-stoplight:
            id: 0q1hdsc073x4b
    Intervention:
      title: Intervention
      x-stoplight:
        id: isocdt4oo7s7y
      type: object
      properties:
        id:
          type: integer
        userSigning:
          $ref: '#/components/schemas/UserSigning'
        share:
          $ref: '#/components/schemas/NoProgrammedShare'
        action:
          type: integer
          x-stoplight:
            id: 4v0eavn531ar2
        startDate:
          type: string
          x-stoplight:
            id: 14nn1910i1mwc
          format: date-time
        endDate:
          type: string
          x-stoplight:
            id: 1blghe5381za3
          format: date-time
        description:
          type: string
          x-stoplight:
            id: b4w2w0bii3k0n
        firstTechnical:
          $ref: '#/components/schemas/User'
        secondTechnical:
          $ref: '#/components/schemas/User'
        signature:
          type: string
          x-stoplight:
            id: 8y6v5dl5jna1k
        operatorSignature:
          type: string
          x-stoplight:
            id: o4vgea6d0oj11
        clientName:
          type: string
          x-stoplight:
            id: y5zosfb602nzz
        materials:
          type: array
          x-stoplight:
            id: 96cv7joi0oiwc
          items:
            x-stoplight:
              id: a9c437a5hksx3
            type: integer
        materialsFile:
          type: string
          x-stoplight:
            id: 8lfzk9pa7wyrg
        materialsFileExt:
          type: string
          x-stoplight:
            id: 790fxpi66ikvh
        equipmentHours:
          type: integer
          x-stoplight:
            id: jlcvcmslrddth
        topicId:
          type: integer
          x-stoplight:
            id: jefh8p0m16cgw
      required:
        - id
        - share
        - action
        - startDate
        - firstTechnical
    NoProgrammedShare:
      title: NoProgrammedShare
      x-stoplight:
        id: nkbdyy6acj6uf
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        project:
          $ref: '#/components/schemas/Project'
        userSigning:
          $ref: '#/components/schemas/UserSigning'
        startDate:
          type: string
          x-stoplight:
            id: yizr915id0hco
          format: date-time
        endDate:
          type: string
          x-stoplight:
            id: hk6tamjfxzyw9
          format: date-time
        description:
          type: string
          x-stoplight:
            id: gdj67dr4ncyyd
        family:
          $ref: '#/components/schemas/Family'
        subFamily:
          $ref: '#/components/schemas/SubFamily'
        topicId:
          type: integer
          x-stoplight:
            id: j8jp9c1aphphk
        forumTitle:
          type: string
          x-stoplight:
            id: l7fu2mhea9mhk
        state:
          type: string
          x-stoplight:
            id: anff5xkbzmal1
          enum:
            - NEW
            - INITIALIZED
            - IN_PROGRESS
            - CLOSED
        lastDiagnosis:
          type: integer
          x-stoplight:
            id: g8rnuovvahzqf
        interventions:
          x-stoplight:
            id: vbc9pywk2s6rp
          type: array
          items:
            $ref: '#/components/schemas/Intervention'
        files:
          type: array
          x-stoplight:
            id: bm1bnujfonrek
          items:
            $ref: '#/components/schemas/ShareFile'
      required:
        - id
        - user
        - project
        - startDate
        - description
        - family
        - subFamily
        - state
    Project:
      title: Project
      x-stoplight:
        id: o6laestj8lfrr
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          x-stoplight:
            id: ll4sov9aexq0v
    ShareFile:
      title: ShareFile
      x-stoplight:
        id: m8bximaz51t4c
      type: object
      properties:
        id:
          type: integer
        fileName:
          type: string
          x-stoplight:
            id: oe2w9nxlwwwkk
        content:
          type: string
          x-stoplight:
            id: prsxmvb3f9spa
          format: byte
      required:
        - id
        - fileName
        - content
    SubFamily:
      title: SubFamily
      x-stoplight:
        id: mw171n2rxxhvr
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          x-stoplight:
            id: lnngd121n48ga
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        mail:
          type: string
        name:
          type: string
        surnames:
          type: string
        country:
          $ref: ../gestepm-master-data-api/api-spec.yaml#/components/schemas/Country
        activityCenter:
          $ref: ../gestepm-master-data-api/api-spec.yaml#/components/schemas/ActivityCenter
        role:
          $ref: ../gestepm-app-config-api/api-spec.yaml#/components/schemas/Role
        level:
          $ref: ../gestepm-master-data-api/api-spec.yaml#/components/schemas/Level
      required:
        - id
        - username
        - mail
    UserSigning:
      title: UserSigning
      x-stoplight:
        id: 0j82spjl8a6od
      type: object
      properties:
        id:
          type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    NoProgrammedShare:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                $ref: ../../base-api-spec.yaml#/components/schemas/Meta
              data:
                $ref: '#/components/schemas/NoProgrammedShare'
    NoProgrammedShareList:
      description: Example response
      content:
        application/json:
          schema:
            properties:
              metadata:
                $ref: ../../base-api-spec.yaml#/components/schemas/Meta
              data:
                type: array
                x-stoplight:
                  id: dyvkfgdppk87v
                items:
                  $ref: '#/components/schemas/NoProgrammedShare'
    UserList:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                $ref: ../../base-api-spec.yaml#/components/schemas/Meta
              data:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    InterventionList:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                $ref: ../../base-api-spec.yaml#/components/schemas/Meta
              data:
                type: array
                items:
                  $ref: '#/components/schemas/Intervention'
    Intervention:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              metadata:
                $ref: ../../base-api-spec.yaml#/components/schemas/Meta
              data:
                $ref: '#/components/schemas/Intervention'
  requestBodies:
    CreateNoProgrammedShare:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                x-stoplight:
                  id: vwybpkwl613hp
                type: integer
              projectId:
                x-stoplight:
                  id: 2juj0v781js7f
                type: integer
              userSigningId:
                x-stoplight:
                  id: n6dwe4xx9tnre
                type: integer
            required:
              - userId
              - projectId
    UpdateNoProgrammedShare:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: integer
              projectId:
                type: integer
              userSigningId:
                type: integer
              startDate:
                type: string
                format: date-time
              endDate:
                type: string
                format: date-time
              description:
                type: string
              familyId:
                type: integer
              subFamilyId:
                type: integer
              topicId:
                type: integer
              forumTitle:
                type: string
              state:
                type: string
                enum:
                  - NEW
                  - INITIALIZED
                  - IN_PROGRESS
                  - CLOSED
              lastDiagnosis:
                type: integer
              files:
                type: array
                items:
                  type: object
                  format: binary
                  properties:
                    name:
                      type: string
                      x-stoplight:
                        id: y4v9ssqe7scoj
                    content:
                      type: string
                      x-field-extra-annotation: '@com.fasterxml.jackson.annotation.JsonIgnore'
                      x-stoplight:
                        id: 6ce64ca1txbth
    CreateIntervention:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: integer
                x-stoplight:
                  id: mo3kufj2a6q8i
              userSigningId:
                type: integer
                x-stoplight:
                  id: g69xyki5xv9nf
              secondTechnicalId:
                type: integer
                x-stoplight:
                  id: nw4vwy5a4j020
              action:
                type: string
                x-stoplight:
                  id: 3wjg8ovua4dpo
                enum:
                  - INTERVENTION
                  - DIAGNOSIS
                  - FOLLOWING
            required:
              - userId
              - action
  parameters:
    Share-Id:
      name: shareId
      in: path
      required: true
      schema:
        type: integer
      description: Share identificator.
tags:
  - name: no-programmed-share-v1
    description: V1 - No Programmed Share
  - name: user-v1
    description: V1 - User
security:
  - basicAuth: []
