context:
  initializer:
    classes: com.epm.gestepm.lib.contextinit.AdditionalYmlPropertiesContextInitializer
    paths-to-load: classpath:/lib-java-defaults/sql/maestros/*, classpath:/sql/application/*, classpath:/sql/gestepm/*, classpath:/sql/master-data/*

data:
  jdbc:
    datasource:
      gestepmds:
        driverClassName: # by environment
        username: # by environment
        password: # by environment
        jdbcUrl: # by environment

gestepm:
  base:
    url: # by environment
  datasource:
    schemas:
      gestepm: bbdd_gestepm
  displacements:
    project-ids: 240, 241
  first-year: 2018
  forum:
    ftp:
      server: # by environment
      port: # by environment
      user: # by environment
      password: # by environment
    url: # by environment
  mails:
    admin: # by environment
    rrhh: # by environment
  signing:
    ftp:
      server: # by environment
      port: # by environment
      user: # by environment
      password: # by environment
    lunch:
      interval:
        start: '13:00'
        end: '16:00'
        time: 45

hibernate:
  dialect: com.epm.gestepm.modelapi.common.utils.mysql.CommonMySQLDialect
  hbm2ddl:
    auto: validate

lib-java:
  app-locale:
    supported-locales-iso: "'ES', 'FR'"
    default-locale: "'ES'"
  cache-keys:
    app-locale: epm.gestepm.app-locale
    app-locale-list: epm.gestepm.app-locale-list
  schemas:
    maestros: bbdd_gestepm

logging:
  config: # by environment
  level:
    root: ERROR
    com.epm.gestepm: INFO
    org.hibernate.SQL: INFO

scheduler:
  personal-signings:
    cron: '0 30 21 * * *'

smtp:
  mail:
    from: info@gestepm.com

spring:
  application:
    name: epm
  datasource:
    jdbcUrl: # by environment
    username: # by environment
    password: # by environment
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: com.epm.gestepm.modelapi.common.utils.mysql.CommonMySQLDialect
    show-sql: false
  mail:
    host: smtp.gestepm.com
    port: 25
    username: info@gestepm.com
    password: O0,c4xYk&!
  messages:
    use-code-as-default-message: true
  profiles:
    default: pro
  second-datasource:
    jdbcUrl: # by environment
    username: # by environment
    password: # by environment
  security:
    user:
      name: user
      password: psw
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  thymeleaf:
    enabled: false

server:
  port: ${port:8888}
  servlet:
    jsp:
      init-parameters.development: true
    session:
      timeout: 60m
      persistent: false