data:
  jdbc:
    datasource:
      gestepmds:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: bbdd_free
        password: A_42BcTiu
        jdbcUrl: jdbc:mysql://92.54.16.198:3306

gestepm:
  base:
    url: https://gestepm.com
  forum:
    ftp:
      server: 92.54.16.198
      port: 22
      user: forum
      password: SQh!Z8ppEdE
    url: http://forum.gestepm.com
  mails:
    admin: jrodriguez@epmgastech.com
    rrhh: jsanchez@epmgastech.com
  signing:
    ftp:
      server: 92.54.16.80
      port: 21
      user: anviz
      password: Anviz_2020

logging:
  config: /var/www/gestepm.com/config/logback-spring.xml

scheduler:
  personal-signings:
    cron: '0 30 21 * * *'

spring:
  datasource:
    jdbcUrl: jdbc:mysql://92.54.16.198:3306/bbdd_gestepm?useSSL=false
    username: bbdd_free
    password: A_42BcTiu
  second-datasource:
    jdbcUrl: jdbc:mysql://92.54.16.198:3306/bbdd_gestepm_forum?useSSL=false
    username: bbdd_forum
    password: AxPGWjwL4!
