data:
  jdbc:
    datasource:
      gestepmds:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: ENC(LswlxuerH82blnC6Euo9fgZTe2TYomFktesFMntrnbU=)
        jdbcUrl: jdbc:mysql://localhost:3306

gestepm:
  base:
    url: http://localhost:8888
  forum:
    ftp:
      server: 92.54.16.198
      port: 22
      user: forum
      password: ENC(prpyOqpA1FcQsH+XXMw2hkNQQRPYQn74)
    url: http://localhost
  mails:
    admin: cardepe@cyxtec.com
    rrhh: cardepe@cyxtec.com
  signing:
    ftp:
      server: 92.54.16.80
      port: 21
      user: anviz
      password: ENC(NYzgQAOhEcIHkL6CsncRrE/S/tnAckZx)
  virtual-project-ids: 251

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/bbdd_gestepm?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ENC(LswlxuerH82blnC6Euo9fgZTe2TYomFktesFMntrnbU=)
  jpa:
    show-sql: true
  second-datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/bbdd_gestepm_forum?useSSL=false
    username: root
    password: ENC(LswlxuerH82blnC6Euo9fgZTe2TYomFktesFMntrnbU=)
