sch-gestepm: ${gestepm.datasource.schemas.gestepm}

sql:

  paginated-query-prefix: |

    SELECT res_.* FROM ( SELECT ROW_NUMBER() OVER() AS rownumber_, temp_.* FROM (

  paginated-query-group-prefix: |

    SELECT res_.* FROM ( SELECT DENSE_RANK() OVER(#orderByToken, id_pagination) AS rownumber_, temp_.* FROM (

  paginated-query-suffix: |

    ) temp_ ) res_
    WHERE rownumber_ BETWEEN :qry_prm_offset + 1 AND :qry_prm_limit + :qry_prm_offset
